
defaults: &defaults
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/dgoldstein1/reverse-proxy
  environment:
    GO111MODULE: "on"

version: 2
jobs:

  ###################
  ## Core Utilties ##
  ###################

  # build go binary and save it to workspace
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go build -o build/reverse-proxy
      - persist_to_workspace:
          root: .
          paths:
            - ./build/reverse-proxy



  #############
  ## Testing ##
  #############

  # run unit tests
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "run unit tests"
          command : |
            go test ./... -coverprofile=coverage.out


      - run:
          name : "Push results to code coverage (master only)"
          command : |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              export CC_TEST_REPORTER_ID=99f460f9ae9925e21a7087b218f317c133406bbb278b2980e6441cdebc79ec01
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter format-coverage ./coverage.out -t gocov
              ./cc-test-reporter upload-coverage
            fi


  # run full integration tests
  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "run integration tests"
          command : |
            cp build/reverse-proxy reverse-proxy
            .circleci/integration_tests.sh
            


  ############################
  ## Tasks for New Releases ##
  ############################

  push-docker-image:
    machine : true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "build and push docker images"
          command : |
              export $(cat VERSION | xargs)
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker build . -t dgoldstein1/reverse-proxy:$VERSION -t dgoldstein1/reverse-proxy:latest
              docker push dgoldstein1/reverse-proxy:$VERSION
              docker push dgoldstein1/reverse-proxy:latest

              docker login --username=$EMAIL --password=$HEROKU_API_KEY registry.heroku.com
              docker tag dgoldstein1/reverse-proxy:$VERSION registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web

  # publish github release with binary
  heroku:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "deploy"
          command: |
              wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
              heroku version
              heroku container:release web --app $HEROKU_APP_NAME


  # publish github release with binary
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      # get binaries
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            export $(cat VERSION | xargs)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/reverse-proxy


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          requires:
      - unit-tests:
          requires:
            - build

      - integration-tests:
          requires:
            - build

      - push-docker-image:
          requires:
            - unit-tests
            - integration-tests
          # filters:
          #   branches:
          #     only: master

      - heroku:
          requires:
            - push-docker-image
          # filters:
          #   branches:
          #     only: master


      - publish-github-release:
          requires:
            - unit-tests
            - integration-tests

          filters:
            branches:
              only: master
