
defaults: &defaults
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/dgoldstein1/custom-reverse-proxy
  environment:
    GO111MODULE: "on"

version: 2
jobs:

  ###################
  ## Core Utilties ##
  ###################

  # build go binary and save it to workspace
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go build -o build/custom-reverse-proxy


  #############
  ## Testing ##
  #############

  # run unit tests
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "run unit tests"
          command : |
            go test ./... -coverprofile=coverage.out


      - run:
          name : "Push results to code coverage (master only)"
          command : |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              export CC_TEST_REPORTER_ID=
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter format-coverage ./coverage.out -t gocov
              ./cc-test-reporter upload-coverage
            fi


  # run full integration tests
  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "run integration tests"
          command : |
            echo "TODO"


  ############################
  ## Tasks for New Releases ##
  ############################

  push-docker-image:
    machine : true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "build and push docker images"
          command : |
              export $(cat VERSION | xargs)
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker build . -t dgoldstein1/custom-reverse-proxy:$VERSION -t dgoldstein1/custom-reverse-proxy:latest
              docker push dgoldstein1/custom-reverse-proxy:$VERSION
              docker push dgoldstein1/custom-reverse-proxy:latest

  # publish github release with binary
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      # get binaries
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            export $(cat VERSION | xargs)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/custom-reverse-proxy


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          requires:
      - unit-tests:
          requires:
            - build

      - integration-tests:
          requires:
            - build

      - push-docker-image:
          requires:
            - unit-tests
            - integration-tests
          filters:
            branches:
              only: master

      - publish-github-release:
          requires:
            - unit-tests
            - integration-tests

          filters:
            branches:
              only: master
